neoforged/websites

assets/js/neoforge.js
=> Add a link to the latest changelog

content/news/20.2registry-rework.md
A few TODOs are left. Team, feel free to change anything.
Preview URL: https://pr-14.neoforged-website-previews.pages.dev
=> Registry rework post

content/news/20.3capability-rework.md, content/news/20.3release.md
Preview URL: https://pr-21.neoforged-website-previews.pages.dev
=> 20.3 update and cap rework

content/_index.md, layouts/shortcodes/projects.html
Preview URL: https://pr-26.neoforged-website-previews.pages.dev
=> Fix index page

themes/mainroad/assets/css/style.css, themes/mainroad/layouts/partials/colors.css
Mostly improved dark theme, but also fixed light theme code colors. Also added a few more color variables in css.
Some before and after screenshots:
Header
- ![Before](https://i.latvian.dev/pc/2024-01-03_17.12.48.png)
- ![After](https://i.latvian.dev/pc/2024-01-03_17.12.55.png)
Code tags, code blocks, slightly rounded buttons
- ![Before](https://i.latvian.dev/pc/2024-01-03_17.13.16.png)
- ![After](https://i.latvian.dev/pc/2024-01-03_17.13.23.png)
Light theme tweaks
- ![Before](https://i.latvian.dev/pc/2024-01-03_17.16.31.png)
- ![After](https://i.latvian.dev/pc/2024-01-03_17.16.47.png)
Preview URL: https://pr-29.neoforged-website-previews.pages.dev
=> Updated website style

content/news/neoforge-snapshots.md
Preview URL: https://pr-31.neoforged-website-previews.pages.dev
=> Snapshots post

content/news/20.5release.md
Preview URL: https://pr-32.neoforged-website-previews.pages.dev
=> 1.20.5 blog post

content/news/21.0release.md
Preview URL: https://pr-41.neoforged-website-previews.pages.dev
=> Fix `inventoryTick` method

content/news/21.0release.md
Preview URL: https://pr-40.neoforged-website-previews.pages.dev
=> Add enum extensions rework to 1.21 blog post

content/news/21.0release.md
Adds additional depluralization directories to the list provided.
Preview URL: https://pr-48.neoforged-website-previews.pages.dev
=> Add missing depluralization directories

hugo.toml, themes/mainroad/layouts/partials/svg/creeperhost.svg
As discussed on Discord, I suggest something like this, happy for wording or whatever to be adjusted.
Preview URL: https://pr-53.neoforged-website-previews.pages.dev
=> Add partner link

content/news/21.2release.md
Preview URL: https://pr-54.neoforged-website-previews.pages.dev
=> Add 21.2 update post

content/news/21.2release.md
Preview URL: https://pr-55.neoforged-website-previews.pages.dev
=> Fix small typo in 1.21.2 blog post

content/news/2024-retrospection.md, data/authors/matyrobbrt.yaml
Preview URL: https://pr-58.neoforged-website-previews.pages.dev
=> 2024 blog post

content/news/moddevgradle2.md
Preview URL: https://pr-59.neoforged-website-previews.pages.dev
=> Add MDG2 blog post

.devcontainer/devcontainer.json, content/news/21.5release.md
Preview URL: https://pr-61.neoforged-website-previews.pages.dev
=> Add 1.21.5 Port Add devcontainer.

content/news/21.5release.md
Corrects a mistake about `equipOnInteract`, updating the description.
Preview URL: https://pr-62.neoforged-website-previews.pages.dev
=> Fix announcement about `equipOnInteract`

content/news/2025serversidesummer.md
Will be updated and released on 6am on the 31st EST (00:00 on the 1st UTC+14)
Preview URL: https://pr-71.neoforged-website-previews.pages.dev
=> 2025 Serverside Summer Announcement

assets/js/neoforge.js
Follow up for https://github.com/neoforged/websites/pull/74 to ensure consistency
=> Fix installer text to stay one liner when changing neo versions

assets/js/neoforge.js, themes/mainroad/assets/css/style.css
This is what it looks like. If all goes well, we will never need to see this lol
Preview URL: https://pr-81.neoforged-website-previews.pages.dev
=> Add fallback instructions so people can use installer when maven is down

assets/js/neoforge.js
=> Fixed Fallback const bug

content/news/21.0release.md
Closes https://github.com/neoforged/websites/issues/84
Preview URL: https://pr-85.neoforged-website-previews.pages.dev
=> Fix networking rework link in 21.0 release page

content/news/2025serversidesummerresults.md
The announcement for 2025 serverside summer contest! 
Preview URL: https://pr-89.neoforged-website-previews.pages.dev
=> Server side summer results

assets/js/neoforge.js
Reworks the version list handler to cache the latest version and a map of minecraft versions to neo versions once. This also fixes an issue where versions like `21.1` would match `21.10` versions.
Preview URL: https://pr-91.neoforged-website-previews.pages.dev
=> Quickly rework neo version list handler
